### PR TITLE
adds pull after fetch

### PR DESCRIPTION
**Pull request by paskino**
addresses #153

### CODE REVIEW

**Comment by paskino** [comment]
@KrisThielemans did we decide anything? I believe we said we'd merge as is, but I might be wrong

**Comment by KrisThielemans** [comment]
you are wrong :-) It won't solve the problem. See description in #153.

**Comment by KrisThielemans** [comment]
@paskino this should be fixed now. I've tried it locally.

**Comment by paskino** [comment]
@KrisThielemans does this mean that we can merge?

**Comment by KrisThielemans** [comment]
as far as I know, yes!

I guess you could try it on your local machine first.

**Pull request merged**
