### PR TITLE
git fetch before checking out SB branch

### LINKED ISSUE #162: UPDATE.sh not fetching non-origin remotes
```
git remote add rijobro https://github.com/rijobro/SIRF-SuperBuild.git
update_VM.sh -s -t rijobro/update_STIR_branch
```
gives:
```
From https://github.com/SyneRBI/SIRF-SuperBuild
   9b69cd0..9c10a11  DISABLE_MatlabOrPython -> origin/DISABLE_MatlabOrPython
 * [new branch]      STIR_v4.0.0            -> origin/STIR_v4.0.0
   0ece523..d0d3b74  conda                  -> origin/conda
 * [new branch]      docker-py3             -> origin/docker-py3
   58ff2ab..903b7da  master                 -> origin/master
 * [new branch]      synerbi_transition     -> origin/synerbi_transition
 * [new branch]      use-gadgetron-317      -> origin/use-gadgetron-317
 * [new branch]      win_fftw_swig_dirs     -> origin/win_fftw_swig_dirs
 * [new branch]      win_osx                -> origin/win_osx
error: pathspec 'rijobro/update_STIR_branch' did not match any file(s) known to git.
```
presumably we could solve this with `git fetch --all` here:
https://github.com/SyneRBI/SyneRBI_VM/blob/762da226c4dc71b585363c63622d93eedccb3ecb/scripts/UPDATE.sh#L174-L177

### PR DESCRIPTION
**Pull request by rijobro**
Fixes #162

### CODE REVIEW

**Comment by KrisThielemans** [comment]
nope. has to be athttps://github.com/SyneRBI/SyneRBI_VM/blob/762da226c4dc71b585363c63622d93eedccb3ecb/scripts/UPDATE.sh#L170

where you're changing things is only used to find the default tag

**Comment by rijobro** [comment]
so should it be `git fetch --tags --all`?

**Comment by KrisThielemans** [comment]
I guess so. try...

**Comment by rijobro** [comment]
yup

**Pull request merged**
